apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-dev
spec:
  selector:
    matchLabels:
      app: pg
  replicas: 1
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
      - name: postgress
        image: postgres:12
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
             name: postgres-config
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - name:  pg-volume
            mountPath:  /var/lib/postgresql/data
      volumes:
        - name:  pg-volume
          persistentVolumeClaim:
            claimName: pg-pvc
---
kind: Service
apiVersion: v1
metadata:
  name:  pg-dev
spec:
  selector:
    app:  pg
  type:  NodePort
  ports:
  - name:  postgres
    port:  5432
    targetPort:  5432

    