apiVersion: v1
kind: Pod
metadata:
  name: svcpod
  labels:
    app: svcpod
spec:
  containers:
    - image: luksa/kubia
      name: kubia
      ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: demo-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: svcpod
---
apiVersion: v1
kind: Service
metadata:
  name: demo-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: svcpod
---
apiVersion: v1
kind: Service
metadata:
  name: demo-default
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: svcpod
---
apiVersion: v1
kind: Service
metadata:
  name: demo-clusterip
spec:
  selector:
    app: svcpod
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

