apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
  labels:
    app: pvdemo
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: default
  persistentVolumeReclaimPolicy: Retain
  azureDisk:
    diskName: xx
    diskURI: xx