apiVersion: v1
kind: Pod
metadata:
  name: pvc-user
spec:
  containers:
    - name: browser
      image: davutozcan/nodews:1
      volumeMounts:
        - mountPath: /opt/output
          name: output
  volumes:
    - name: output
      persistentVolumeClaim:
        claimName: demo-pvc